name: Python CI

# Trigger the Workflow on any push to the main branch or pull request

on:
    push:
        branches: 
            - main
    pull_request:
        branches: 
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # step1: checkout the code from repository
            - name: Check out code
              uses: actions/checkout@v2

            #step2: Set up python Environment
            - name: Setu up Environment
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'

            #step3: Install dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # step4: Run pytest
            - name: Run pytest
              run: |
                  pytest
